# -*- coding: utf-8 -*-
"""
Created on Sat May 22 09:53:23 2021

@author: torid
"""

# can update to pull names for two files instead

# export these names to a list to not take up so much space in this file
firstnames = [
        'Fannie','Troy','Fanny','Fanie','Troi','Rebecca','Rebeka','Rebekka','Eila',
         'Evilyn','Evelyinne','Evelyn-Anne','Khadija', 'Charlotte', 'Ffion', 
         'Josie', 'Chantelle','Sam','Rhayondra','Raye','Rahonda','Chadrana','Sharona',
         'Shana','Shona','Telay','Neelay','Milly','Millie','Michelle','Fannie',
         'Callum','Bryn','Byron','Biron','Calypso','Hermione','Georgia','Danielle', 
         'Cerys','Cyrus', 'Cyprus','Mia','Mila','Mya','Genevieve','Karen','Constance',
         'Callie (Calla)','Demi', 'Anita', 'Charley', 'Millicent', 'Esther', 
         'Scarlett', 'Nellie', 'Terry', 'Victoria', 'Hollie','Michaela', 'Annalise',
         'Maha', 'Nadjiba', 'Yasmine', 'Ali', 'Rahma', 'Chakira', 'Douha', 
         'Habiba', 'Sanaa', 'Saliha', 'Safia', 'Mabrouka', 'Khalida', 'Maha', 
         'Faten', 'Hawa', 'Manel', 'Mahbouba','Amine', 'Mouna', 'Djamila', 
         'Fouzia', 'Warda', 'Hafsa', 'Samira', 'Naziha', 'Nawel', 'Wafa', 
         'Hafida', 'Meriem', 'Ikram', 'Ilhem', 'Sakina', 'Siheme', 'Selma', 
         'Afaf', 'Sakina', 'Fadila', 'Hani', 'Soraya', 'Majda', 'Aziza', 
         'Emna', 'Wahiba', 'Halima', 'Aicha', 'Sanaa', 'Basma','Saida', 
         'Faten', 'Saliha', 'Yousra', 'Hauled', 'Imane', 'Halima', 
         'Wasilla', 'Habiba', 'Sami', 'Hadia', 'Anise', 'Zineb', 'Ghania', 
         'Ibtissem', 'Assia', 'Nafissa', 'Samira', 'Khadidja', 'Ahlem', 'Malika', 
         'Hanane', 'Nedjma', 'Abida', 'Nadjiba', 'Aissa', 'Ghalia', 'Habiba', 
         'Hilal', 'Douha', 'Sanaa', 'Souad', 'Nadia', 'Aya', 'Rachida', 'Amira', 
         'Hania', 'Hawa', 'Asma', 'Hani', 'Samia', 'HafidaMouna', 'Fouzia', 
         'Kawtar','Rahma', 'Fatiha', 'Samia', 'Aida', 'Amana', 
         'Naziha', 'Chahrazad', 'Chakira', 'Najet', 'Rajah', 'Yousra', 
         'Nabila', 'Zohra', 'Salima', 'Adel', 'Imane', 'Sakina', 'Ikram', 
         'Amel', 'Nacira', 'Yousra', 'Malika', 'Sami', 'Saloua', 'Afaf', 
         'Yamina', 'Rahma', 'Abida', 'Hani', 'Hamida', 'Moufida', 'Basma', 
         'Mounira', 'Samia', 'Zohra', 'Afifa','Meriem', 'Rayan', 
         'Badra', 'Aissa', 'Najet', 'Maissa', 'Wasilla', 'Nour', 
         'Faiza', 'Najet', 'Meriem', 'Ali', 'Aissa', 'Najet', 'Maissa', 
         'Russell', 'Muhammed', 'Danny', 'Jasper', 'Reuben', 'Casey', 'Caleb', 
         'Jamal', 'Paul', 'Herbert', 'Gerald', 'Omar', 'Dale', 'Sienna',
         'Willard', 'Jerry', 'Billy', 'Rebekah', 'Maxim', 'Stephen', 'Abdul', 
         'Stevie', 'Dan', 'Daniel', 'Daynei', 'Danie', 'Stevy', 'Adrian', 'Carlos',
         'Todd', 'Phillip', 'Guy', 'Hamish', 'Ronald', 'Marshall', 'Ahmad', 
         'Marcel', 'Richard', 'Brendan', 'Marcelle', 'Nadia', 'Jimmy', 'Kristian',
         'Gregory', 'Verity', 'Xavier','Deion', 'Deiondre', 'Dele', 'Denzel', 
         'Dewayne', 'Dikembe', 'Durante', 'Jamar', 'Jevonte', 'Kadeem', 'Kendis', 
         'Kentay', 'Keshawn', 'Khalon', 'Kofi', 'Kwamin', 'Kyan', 'Kyrone', 'LaVonn', 
         'Lado', 'Laken', 'Lakista', 'LamechLavaughn', 'LeBronLisimba', 'Ludacris', 
         'Mablevi', 'Marques', 'Mashawn', 'Montraie', 'Mykelti', 'Nabulung', 'Naeem', 
         'Napoleon', 'Obiajulu', 'Quaashie', 'Quaddus', 'Quadrees', 'Quannell', 
         'Quarren', 'Quashawn', 'Quintavius', 'Quoitrel', 'Raimy', 'Rashon', 'Razi', 
         'Roshaun', 'Runako', 'Salim', 'Cassietta', 'Cleotha', 'Deiondre', 'Dericia',
         'Gaynelle', 'Kacondra', 'Kanesha', 'Keilantra', 'Kendis', 'Keshon', 'Lachelle', 
         'Lakin', 'Lanelle', 'Laquanna', 'Laqueta', 'Laquinta', 'Lashawn', 'Latanya', 
         'Latonya', 'Latoya', 'Mekell', 'Moesha', 'Muncel', 'Najwa', 'Nakeisha', 
         'Nichelle', 'Niesha', 'Quanella', 'Quanesha', 'Quisha', 'Ranielle', 'Ronnell', 
         'Shandra', 'Shaquana', 'Shateque', 'Sidone', 'Talaitha', 'Talisa', 'Talisha', 
         'Tamika', 'Tamira', 'Tamyra', 'Tanasha', 'Tandice', 'Tanginika', 'Taniel', 
         'Tanisha', 'Tariana', 'Temima', 'Winnifred', 'Winny', 'Winona', 'Winonah', 
         'Wren', 'Wrennie', 'Wylma', 'Wynn', 'Wynne', 'Wynnie', 'Wynny', 'Xaviera', 
         'Xena', 'Xenia', 'Xylia', 'Xylina', 'Yalonda', 'Yasmeen', 'Yasmin', 'Yelena',
         'Yetta', 'Yettie', 'Yetty', 'Yevette', 'Ynes', 'Ynez', 'Yoko', 'Yolanda', 
         'Yolande', 'Yolane', 'Yolanthe', 'Yoshi', 'Yoshiko', 'Yovonnda', 'Ysabel', 
         'Yvette', 'Yvonne', 'Zabrina', 'Zahara', 'Zandra', 'Zaneta', 'Zara', 'Zarah',
         'Zaria', 'Zarla', 'Zea', 'Zelda', 'Zelma', 'Zena', 'Zenia', 'Zia', 'Zilvia', 
         'Zita', 'Zitella', 'Zoe', 'Zola', 'Zonda', 'Zondra', 'Zonnya', 'Zora', 
         'Zorah', 'Zorana', 'Zorina', 'Zorine', 'ZsaZsa', 'Zsazsa', 'Zulema',
         'Zuzana','Timmie', 'Timmy', 'Timothea', 'Tina', 'Tine', 'Tiphani', 
         'Tiphanie', 'Tiphany', 'Tish', 'Tisha', 'Tobe', 'Tobey', 'Tobi', 'Toby', 
         'Tobye', 'Toinette', 'Toma', 'Tomasina', 'Tomasine', 'Tomi', 'Tommi', 
         'Tommie', 'Tommy', 'Toni', 'Tonia', 'Tonie', 'Tony', 'Tonya', 'Tonye', 
         'Tootsie', 'Torey', 'Tori', 'Torie', 'Torrie', 'Tory', 'Tova', 'Tove', 
         'Tracee', 'Tracey', 'Traci', 'Tracie', 'Tracy', 'Trenna', 'Tresa', 'Trescha',
         'Tressa', 'Tricia', 'Trina', 'Trish', 'Trisha', 'Trista', 'Trix', 'Trixi', 
         'Trixie', 'Trixy', 'Truda', 'Trude', 'Trudey', 'Trudi', 'Trudie', 'Trudy', 
         'Trula', 'Tuesday', 'Twila', 'Twyla', 'Tybi', 'Tybie', 'Tyne', 'Ula', 'Ulla',
         'Ulrica', 'Ulrika', 'Ulrikaumeko', 'Ulrike', 'Umeko', 'Una', 'Ursa',
         'Ursala', 'Ursola', 'Ursula', 'Ursulina', 'Ursuline', 'Uta', 'Val', 
         'Valaree', 'Valaria', 'Vale', 'Valeda', 'Valencia', 'Valene', 'Valenka', 
         'Valentia', 'Valentina', 'Valentine', 'Valera', 'Valeria', 'Valerie', 
         'Valery', 'Valerye', 'Valida', 'Valina', 'Valli', 'Vallie', 'Vally', 'Valma', 
         'Valry', 'Van', 'Vanda', 'Vanessa', 'Vania', 'Vanna', 'Vanni', 'Vannie', 
         'Vanny', 'Vanya', 'Veda', 'Velma', 'Velvet', 'Venita', 'Venus', 'Vera', 
         'Veradis', 'Vere', 'Verena', 'Verene', 'Veriee', 'Verile', 'Verina', 
         'Verine', 'Verla', 'Verna', 'Vernice', 'Veronica', 'Veronika', 'Veronike',
         'Veronique', 'Vevay', 'Vi', 'Vicki', 'Vickie', 'Vicky', 'Victoria', 'Vida', 
         'Viki', 'Vikki', 'Vikky', 'Vilhelmina', 'Vilma', 'Vin', 'Vina', 'Vinita', 
         'Vinni', 'Vinnie', 'Vinny', 'Viola', 'Violante', 'Viole', 'Violet', 
         'Violetta', 'Violette', 'Virgie', 'Virgina', 'Virginia', 'Virginie', 'Vita',
         'Vitia', 'Vitoria', 'Vittoria', 'Viv', 'Viva', 'Vivi', 'Vivia', 'Vivian', 
         'Viviana', 'Vivianna', 'Vivianne', 'Vivie', 'Vivien', 'Viviene', 'Vivienne',
         'Viviyan', 'Vivyan', 'Vivyanne', 'Vonni', 'Vonnie', 'Vonny', 'Vyky', 
         'Wallie', 'Wallis', 'Walliw', 'Wally', 'Waly', 'Wanda', 'Wandie', 'Wandis', 
         'Waneta', 'Wanids', 'Wenda', 'Wendeline', 'Wendi', 'Wendie', 'Wendy', 
         'Wendye', 'Wenona', 'Wenonah', 'Whitney', 'Wileen', 'Wilhelmina', 
         'Wilhelmine', 'Wilie', 'Willa', 'Willabella', 'Willamina', 'Willetta', 
         'Willette', 'Willi', 'Willie', 'Willow', 'Willy', 'Willyt', 'Wilma', 
         'Wilmette', 'Wilona', 'Wilone', 'Wilow', 'Windy', 'Wini','Keykoria',
        'Aconitum', 'Gazania', 'African', 'Daisy', 'Gazania', 
        'Agapanthus', 'Postbloom', 'Agapanthus', 'Ageratum', 'houstonianum', 
        'Blue', 'Mink', 'Compositae', 'Ageratum', 'houstonianum', 
        'Floss', 'Alchemilla', 'alpine', 'Alchemilla', 'Mantle', 'Allium', 
        'roseum', 'Pisa', 'Allium', 'roseum', 'Onion', 'Garlic', 'Alstroemeria', 
        'aurea', 'Saturne', 'Alstroemeria', 'Iceland', 'Plants', 'Alyssum', 'Sweet', 
        'Alyssum', 'Amaranthus', 'Amaranthus', 'Princes', 'Feather', 'Amaryllis', 
        'Hippeastrum', 'Amaryllis', 'Hippeastrum', 'Anemone', 'Anemone', 
        'Windflower', 'Angelonia', 'Salicariifolia', 'Angelonia', 'Summer', 
        'Snapdragon', 'Anthurium1', 'Anthurium', 'Flamingo', 
        'Flamingo-Snapdragons', 'Antirrhinum', 'majus', 'Snapdragon',
        'Aquilegia', 'pyrenaica', 'Aquilegia', 'Columbine', 'Grannys', 'Bonnet', 
        'Purple', 'Milkweed', 'Asclepias', 'purpurascens', 'Ant', 'Asclepias', 
        'Syriaca', 'Purple', 'Milkweed', 'Aster', 'Amellus', 'Daisy', 'Family', 
        'Asteraceae', 'Astilbes','Aberaeron', 'Aberavon', 'Aberbargoed', 'Abercarn', 'Aberdare', 'Abergavenny',
        'Abergele', 'Abertillery', 'Aberystwyth', 'Amlwch', 'Ammanford', 'Bagillt', 
        'Bala', 'Bangor', 'Bargoed', 'Barmouth', 'Barry', 'Beaumaris', 'Bedwas', 
        'Bethesda', 'Blaenau', 'Ffestiniog', 'Blaenavon', 'Blackwood', 'Blaina', 
        'Brecon', 'Bridgend', 'Briton', 'Ferry', 'Brynmawr', 'Buckley', 'Builth', 
        'Wells', 'Burry', 'Port', 'Caerleon', 'Caernarfon', 'Caerphilly', 'Caerwys', 
        'Caldicot', 'Cardiff', 'Cardigan', 'Carmarthen', 'Chepstow', 'Chirk', 'Colwyn',
        'Bay', "Connah's", 'Quay', 'Conwy', 'Corwen', 'Cowbridge', 'Criccieth', 
        'Crickhowell', 'Crumlin', 'Cwmbran', 'Ferndale', 'Fishguard', 'Flint', 
        'Harlech', 'Haverfordwest', 'Hay-on-Wye', 'Holt', 'Holyhead', 'Holywell', 
        'Kidwelly', 'Knighton', 'Lampeter', 'Laugharne', 'Llandeilo', 'Llandovery', 
        'Llandrindod', 'Wells', 'Llandudno', 'Llandudno', 'Junction', 'Llandysul',
        'Llanelli', 'Llanfair', 'Caereinion', 'Llanfairfechan', 'Llanfyllin', 
        'Llangefni', 'Llangollen', 'Llanidloes', 'Llanrwst', 'Llantrisant',
        'Llantwit', 'Major', 'Llanwrtyd', 'Wells', 'Llanybydder', 'Loughor', 
        'Pembroke', 'Pembroke', 'Dock', 'Penarth', 'Pencoed', 'Penmaenmawr', 
        'Penrhyn', 'Bay', 'Pontardawe', 'Pontarddulais', 'Pontypool', 'Pontypridd', 
        'Port', 'Talbot', 'Porth', 'Porthcawl', 'Porthmadog', 'Prestatyn', 
        'Presteigne', 'Pwllheli'    
        ]
# source: familyeducation.com
lastnames = [
        'Caldwell', 'Bates', 'Sterling', 'Trenton', 'Yorke', 'Redbird', 'Hale', 
        'Valatieri', 'Molloy', 'Force', 'Shiki', 'Belcourt', 'Stark', 'Munster', 
        'Damaskinos', 'Desperado', 'Von-humpeding', 'Hio', 'Thornton', 'Brunestud', 'Ferenc', 
        'Dornez', 'Pratt', 'Gilbert', 'Orlok', 'Cutter', 'Herrick', 'Ver', 'Zachs', 'Voldaren', 
        'Lockwood', 'Molloy', 'Sturges', 'Eltnam', 'Caruso', 'Brando','Woolums', 'Salvatore', 
        'Fier', 'Infinite', 'Edelmann', 'Saushkin', 'Salvatore', 'Brabec', 'Mephistopheles', 
        'More', 'Vanchure', 'Holtz', 'Lykan', 'Boris', 'Renfield', 'Takano', 'Varney', 'Blake', 
        'Glass', 'Belmont', 'Dansby', 'Romanus', 'Dalton', 'Henry', 'Rinaldi', 'Zaleska', 
        'Sorel', 'Phelps', 'Antoniou', 'Beck', 'Papadopoulos', 'Barker', 'Dimitriadis', 
        'Kelly', 'Georgiou', 'Bush', 'Papadakis', 'Torres', 'Nikolaidis', 'Guzman', 
        'Alexander', 'Curry', 'Vlahos', 'Miles', 'Angelopoulos', 'Tucker', 'Athanasiadis', 
        'Pierce', 'Petridis', 'Pearson', 'Papantoniou', 'Lyons', 'Thomas', 'Walsh', 
        'Panagiotopoulos', 'Finch', 'Mckinney', 'Howells', 'Willis', 'Shelton', 'Reynolds', 
        'Hudson', 'Abbas', 'Adam', 'Kaur', 'Begum', 'Gallo', 'Higgins', 'Lucas', 'Gomez', 'Martin', 
        'Mueller', 'Mitchell', 'Lee', 'Moreno', 'Ayala', 'Conti', 'Meyer', 'Fontana', 
        'Goodman', 'Lombardi', 'Nelson', 'Moretti', 'Ortega', 'Esposito', 'James', 
        'Caruso', 'Guzman', 'Rinaldi', 'Molina', 'Giordano', 'Bowers', 'Rossi', 'Rhodes', 
        'Santoro', 'Wall', 'Colombo', 'Reeves', 'Ricci', 'Heath', 'Manuel', 'Cohen', 'Bianchi', 
        'Harrison', 'Russo', 'Freeman', 'Mariani', 'Gilbert', 'Barbieri', 'Patterson,', 'Bruno', 
        'Hunter', 'Aaberg', 'Aaby', 'Aadland', 'Aagaard', 'Aagard', 'Aaker', 'Aakre', 
        'Aalbers', 'Aalto', 'Aamodt', 'Aamot', 'Aanenson', 'Aardema', 'Aarhus', 'Aaron', 
        'Aarons', 'Aaronson', 'Aas', 'Aase', 'Aasen', 'Abad', 'Abadi', 'Abadie', 'Abair', 
        'Abajian', 'Abalos', 'Abar', 'Abarca', 'Abare', 'Abascal', 'Abate', 'Abato', 'Abbas', 
        'Abbasi', 'Abbate', 'Abbatiello', 'Abbe', 'Abbett', 'Abbey', 'Abbitt', 'Abbot', 'Abbott', 
        'Abboud', 'Abbruzzese', 'Abbs', 'Abbuhl', 'Abby', 'Abdalla', 'Abdallah', 'Abdella', 
        'Abdelnour', 'Abdelrahman', 'Abdi', 'Abdo', 'Abdon', 'Abdoo', 'Abdou', 'Abdul', 'Abdulla', 
        'Abdullah', 'Abe', 'Abebe', 'Abed', 'Abee', 'Abegg', 'Abegglen', 'Abeita', 'Abel', 
        'Abela', 'Abele', 'Abeles', 'Abell', 'Abella', 'Abello', 'Abelman', 'Abeln', 'Abels', 
        'Abelson', 'Abend', 'Abendroth', 'Aber', 'Abercrombie', 'Aberg', 'Aberle', 'Aberman', 
        'Abernathey', 'Abernathy', 'Abernethy', 'Abert', 'Abeyta', 'Abid', 'Abila', 'Abitz', 
        'Abke', 'Able', 'Ableman', 'Abler', 'Ables', 'Abner', 'Abney','Paap', 'Paape', 
        'Paar', 'Paas', 'Paasch', 'Paavola', 'Paben', 'Pabian', 'Pabich', 'Pabis', 
        'Pablo', 'Pabon', 'Pabst', 'Pac', 'Pacana', 'Paccione', 'Pace', 'Pacek', 
        'Pacella', 'Pacelli', 'Pacer', 'Pacetti', 'Pacey', 'Pach', 'Pacha', 'Pache', 
        'Pacheco', 'Pachl', 'Pacholski', 'Pachter', 'Pachucki', 'Pachuta', 'Paci', 
        'Paciello', 'Pacific', 'Pacifico', 'Pacilio', 'Pacini', 'Pacino', 'Pacione', 
        'Paciorek', 'Pacitti', 'Pacitto', 'Pack', 'Packard', 'Packer', 'Packett', 
        'Packham', 'Packman', 'Packwood', 'Pacocha', 'Pacyna', 'Paczkowski', 
        'Padalino', 'Padberg', 'Paddack', 'Padden', 'Paddock', 'Paddy', 'Padelford', 
        'Paden', 'Paderewski', 'Padfield', 'Padget', 'Padgett', 'Padgham', 'Padgitt', 
        'Padilla', 'Padin', 'Padley', 'Padlo', 'Padmanabhan', 'Padmore', 'Pado', 'Padon', 
        'Padovani', 'Padovano', 'Padrick', 'Padro', 'Padron', 'Padua', 'Paduano', 'Paduch',
        'Padula', 'Pae', 'Paek', 'Paepke', 'Paes', 'Paeth', 'Paetow', 'Paetz', 'Paetzold', 
        'Paez', 'Paff', 'Pafford', 'Paffrath', 'Pagac', 'Pagan', 'Paganelli', 'Pagani',
        'Emelita', 'Emelyne', 'Emera', 'Emilee', 'Emili', 'Emilia', 'Emilie', 'Emiline', 
        'Emily', 'Emlyn', 'Emlynn', 'Emlynne', 'Emma', 'Emmalee', 'Emmaline', 'Emmalyn', 
        'Emmalynn', 'Emmalynne', 'Emmeline', 'Emmey', 'Emmi', 'Emmie', 'Emmy', 'Emmye', 
        'Emogene', 'Emyle', 'Emylee', 'Engracia', 'Enid', 'Enrica', 'Enrichetta', 'Enrika', 'Enriqueta', 
        'Eolanda', 'Eolande', 'Eran', 'Erda', 'Erena', 'Erica', 'Ericha', 'Ericka', 'Erika', 'Erin', 'Erina', 
        'Erinn', 'Erinna', 'Erma', 'Ermengarde', 'Ermentrude', 'Ermina', 'Erminia', 'Erminie', 'Erna', 'Ernaline', 
        'Ernesta', 'Ernestine', 'Ertha', 'Eryn', 'Esma', 'Esmaria', 'Esme', 'Esmeralda', 'Essa', 'Essie', 'Essy', 'Esta', 
        'Estel', 'Estele', 'Estell', 'Estella', 'Estelle', 'Ester', 'Esther', 'Estrella', 'Estrellita', 'Ethel', 'Ethelda', 
        'Ethelin', 'Ethelind', 'Etheline', 'Ethelyn', 'Ethyl', 'Etta', 'Etti', 'Ettie', 'Etty', 'Eudora', 'Eugenia', 'Eugenie',
        'Oliver', 'Montgomery', 'Richards', 'Williamson', 'Johnston', 'Banks', 'Meyer', 'Bishop', 'Mccoy', 'Howell', 
        'Alvarez', 'Morrison', 'Hansen', 'Fernandez', 'Garza', 'Harvey', 'Little', 'Burton', 'Stanley', 'Nguyen', 
        'George', 'Jacobs', 'Reid', 'Kim', 'Fuller', 'Lynch', 'Dean', 'Gilbert', 'Garrett', 'Romero', 'Welch', 'Larson', 
        'Frazier', 'Burke', 'Hanson', 'Day', 'Mendoza', 'Moreno', 'Bowman', 'Medina', 'Fowler', 
        'Brewer', 'Hoffman', 'Carlson', 'Silva', 'Pearson', 'Holland', 'Douglas', 'Fleming', 'Jensen', 'Vargas', 'Byrd', 'Davidson',
        'Hopkins', 'May', 'Terry', 'Herrera', 'Wade', 'Soto', 'Walters', 'Curtis', 'Neal', 'Caldwell', 'Lowe', 'Jennings', 'Barnett', 'Graves', 'Jimenez', 
        'Horton', 'Shelton', 'Barrett', 'Obrien', 'Castro', 'Sutton', 'Gregory', 'Mckinney', 'Lucas', 'Miles', 'Craig', 'Rodriquez', 'Chambers', 'Holt', 'Lambert', 
        'Fletcher', 'Watts', 'Bates', 'Hale', 'Rhodes', 'Pena', 'Beck', 'Newman', 'Haynes', 'Mcdaniel', 'Mendez', 'Bush', 'Vaughn', 'Parks', 'Dawson', 'Santiago', 'Norris', 
        'Hardy', 'Love', 'Steele', 'Curry', 'Powers', 'Schultz', 'Barker', 'Guzman', 'Page', 'Munoz', 'Ball', 'Keller', 'Chandler', 'Weber', 'Leonard', 'Walsh', 'Lyons', 'Ramsey', 
        'Wolfe', 'Schneider', 'Mullins', 'Benson', 'Sharp', 'Bowen', 'Daniel', 'Barber', 'Cummings', 'Hines', 'Baldwin', 'Griffith', 'Valdez', 
        'Hubbard', 'Salazar', 'Reeves', 'Warner', 'Stevenson', 'Burgess', 'Santos', 'Tate', 'Cross', 'Garner', 'Mann', 'Mack', 'Moss', 'Thornton', 
        'Dennis', 'Mcgee', 'Farmer', 'Delgado', 'Aguilar', 'Vega', 'Glover', 'Manning', 'Cohen', 'Harmon', 'Rodgers', 'Robbins', 'Newton', 'Todd', 'Blair', 'Higgins', 
        'Ingram', 'Reese', 'Cannon', 'Strickland', 'Townsend', 'Potter', 'Goodwin', 'Walton', 'Rowe', 'Hampton', 'Ortega', 'Patton', 'Swanson', 'Joseph', 
        'Francis', 'Goodman', 'Maldonado', 'Yates', 'Becker', 'Erickson', 'Hodges', 'Rios', 'Conner', 'Adkins', 'Webster', 'Norman', 'Malone', 
        'Hammond', 'Flowers', 'Cobb', 'Moody', 'Quinn', 'Blake', 'Maxwell', 'Pope', 'Floyd', 'Osborne', 'Paul', 'Mccarthy', 'Guerrero', 'Lindsey', 'Estrada', 
        'Sandoval', 'Gibbs', 'Tyler', 'Gross', 'Fitzgerald', 'Stokes'
    ]

# count the names 
# print("There are ", len(lastnames), " in the last/family name lists.")
# print("There are ", len(firstnames), "firstnames")
# print(len(lastnames) + len(firstnames), " total names.")
